name: splinecam
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - arpack=3.7.0=hdefa2d7_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost=1.74.0=py38h2b96118_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h0a891b7_1005
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - cairomm=1.14.4=ha770c72_0
  - cairomm-1.0=1.14.4=h09cb3b9_0
  - certifi=2022.9.24=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=38.0.2=py38h80a4ca7_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.4.1.50=hed8a83a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - epoxy=1.5.10=h166bdaf_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.8=hff1cb4f_1
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h7b6447c_0
  - glib-tools=2.74.1=h6239696_0
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h295c915_3
  - graph-tool=2.45=py38h7041675_2
  - graph-tool-base=2.45=py38hba1c032_2
  - graphite2=1.3.14=h295c915_1
  - gtk3=3.24.34=h4d20fae_1
  - harfbuzz=5.3.0=h418a68e_0
  - hicolor-icon-theme=0.17=h06a4308_2
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.15.2=py38h06a4308_0
  - ipython=8.4.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.16.0=py38h06a4308_0
  - jupyter_client=7.3.5=py38h06a4308_0
  - jupyter_core=4.11.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py38h295c915_0
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=16_linux64_openblas
  - libcups=2.3.3=h3e49a29_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.4.2=h295c915_4
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgirepository=1.74.0=ha2a38d2_1
  - libglib=2.74.1=h7a41b64_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.38=h753d276_0
  - libprotobuf=3.21.9=h6239696_0
  - librsvg=2.54.4=h7abd40a_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=hecacb30_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.3=h295c915_1
  - magma=2.5.4=hc72dce7_3
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-base=3.5.2=py38hf590b9c_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - metis=5.1.0=h58526e2_1006
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2022.1.0=hc2b9512_224
  - mpfr=4.1.0=h9202a9a_1
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.5.0=py38h06a4308_0
  - nccl=2.14.3.1=h0800d71_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py38h06a4308_0
  - networkx=2.8.4=py38h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - notebook=6.4.12=py38h06a4308_0
  - numpy=1.23.4=py38h7042d01_1
  - openssl=3.0.5=h166bdaf_2
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.11=h382ae3d_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.37=he7ceb23_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.2.2=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkgutil-resolve-name=1.3.10=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycairo=1.21.0=py38h287db57_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pygobject=3.42.2=py38h6284730_1
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.13=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-igraph=0.10.2=py38h3805f6d_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=cuda112py38hd94e077_201
  - pyzmq=23.2.0=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scikit-learn=1.1.3=py38h6a678d5_0
  - scipy=1.9.3=py38h8ce737c_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=63.4.1=py38h06a4308_0
  - sigcpp-2.0=2.10.8=h27087fc_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h9b69904_2
  - soupsieve=2.3.2.post1=py38h06a4308_0
  - sparsehash=2.0.4=h9c3ff4c_0
  - sqlite=3.39.3=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - suitesparse=5.10.1=h9e50725_1
  - tbb=2021.6.0=h924138e_1
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.6.0=py38h06a4308_0
  - texttable=1.6.4=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.13.0=cuda112py38h53e7b36_0
  - tornado=6.2=py38h5eee18b_0
  - tqdm=4.64.1=py38h06a4308_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py38h06a4308_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.6=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py38h06a4308_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.18.0=py38h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - bokeh==3.0.1
    - contourpy==1.0.6
    - livelossplot==0.5.5
    - pandas==1.5.1
    - pytz==2022.6
    - pyyaml==6.0
    - xyzservices==2022.9.0
prefix: /home/ah73/anaconda3/envs/splinecam
